# SPDX-FileCopyrightText: 2017 Scott Shawcroft, written for Adafruit Industries
#
# SPDX-License-Identifier: Unlicense

version: 2

build:
    os: ubuntu-22.04
    tools:
        python: "3.11"

sphinx:
    configuration: docs/conf.py

python:
    install:
        - requirements: requirements.txt
